"""
EvidenceAtom schema — AUDIT-015 fix.

page_no is mandatory and must come from real PDF parser metadata,
never generated by LLM.
"""
from __future__ import annotations

from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator


class EvidenceAtom(BaseModel):
    """
    An atomic unit of evidence extracted from a PDF page.

    [AUDIT-015] page_no is REQUIRED and must be populated from
    pdfplumber.pages index — LLMs must NEVER generate this value.
    The field is validated against the parsed page pool by
    post_validate_evidence_page().
    """

    evidence_id: UUID = Field(
        default_factory=uuid4,
        description="Unique evidence atom ID (UUID4, not LLM-generated)",
    )
    paper_id: str = Field(..., description="OpenAlex Work ID or arXiv ID")
    # [AUDIT-015] page_no is mandatory — must come from pdfplumber page index
    page_no: int = Field(
        ...,
        ge=1,
        description=(
            "[AUDIT-015] Real PDF page number from pdfplumber.pages index. "
            "Must NEVER be assigned by LLM. Validated by post_validate_evidence_page()."
        ),
    )
    span_text: str = Field(
        ...,
        min_length=10,
        max_length=2000,
        description="Extracted text span (±1 sentence context per AUDIT-057)",
    )
    section_type: str = Field(
        ...,
        description="Section: limitations|discussion|conclusion|future_work|abstract|body",
    )
    parser: str = Field(
        default="pdfplumber",
        description="Parser used: pdfplumber|nougat|grobid",
    )
    content_hash: Optional[str] = Field(
        None,
        description="SHA-256 of span_text (anti-hallucination)",
    )

    @model_validator(mode="after")
    def compute_hash_if_missing(self) -> "EvidenceAtom":
        """Auto-compute content_hash from span_text if not provided."""
        if self.content_hash is None:
            import hashlib
            self.content_hash = hashlib.sha256(
                self.span_text.encode("utf-8")
            ).hexdigest()
        return self
