"""
PDF parser — AUDIT-015 fix: page_no metadata from pdfplumber.

V11.1 bug: page numbers were either absent or generated by the LLM,
allowing hallucinated page references.

V11.2 fix:
- parse_pdf_pages() uses pdfplumber and records the REAL page index
  (1-based) for every text block.
- The page_no field is populated from pdfplumber.pages, never from LLM.
- post_validate_evidence_page() rejects any LLM output whose page_no
  is not in the set of pages actually parsed from the document.
"""
from __future__ import annotations

import logging
import re
from typing import Iterator, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Page-annotated text block
# ---------------------------------------------------------------------------

class PageBlock:
    """A chunk of text with its real PDF page number."""

    __slots__ = ("page_no", "text", "section_hint")

    def __init__(self, page_no: int, text: str, section_hint: str = "body") -> None:
        if page_no < 1:
            raise ValueError(f"page_no must be ≥ 1, got {page_no}")
        self.page_no = page_no        # real page from pdfplumber
        self.text = text
        self.section_hint = section_hint  # abstract|body|limitations|…

    def __repr__(self) -> str:
        return f"PageBlock(page={self.page_no}, chars={len(self.text)}, section={self.section_hint!r})"


# ---------------------------------------------------------------------------
# PDF parsing
# ---------------------------------------------------------------------------

_SECTION_PATTERNS: dict[str, re.Pattern] = {
    "abstract":    re.compile(r"^\s*abstract\s*$", re.I | re.M),
    "limitations": re.compile(r"^\s*(limitation|limitation[s]?|future\s+work|discussion)\s*$", re.I | re.M),
    "conclusion":  re.compile(r"^\s*(conclusion[s]?|concluding\s+remarks?)\s*$", re.I | re.M),
}


def parse_pdf_pages(pdf_path: str) -> list[PageBlock]:
    """
    Parse a PDF and return a list of PageBlock objects, each with the REAL
    page number from pdfplumber.pages.

    [AUDIT-015] This is the authoritative source of page_no.
    Downstream code (LLM prompts, EvidenceAtom) MUST use these values;
    LLMs must NEVER invent page numbers.

    Args:
        pdf_path: Absolute path to the PDF file.

    Returns:
        List of PageBlock objects ordered by page.
    """
    blocks: list[PageBlock] = []
    parser_used = None

    try:
        import pdfplumber  # type: ignore
        parser_used = "pdfplumber"
        with pdfplumber.open(pdf_path) as pdf:
            for idx, page in enumerate(pdf.pages):
                # [AUDIT-015] page_no = parser index (1-based)
                page_no = idx + 1
                text = page.extract_text()
                if not text:
                    continue

                # Detect section type heuristically
                section = "body"
                for sec_name, pattern in _SECTION_PATTERNS.items():
                    if pattern.search(text[:200]):
                        section = sec_name
                        break

                blocks.append(PageBlock(page_no=page_no, text=text, section_hint=section))
    except ImportError:
        pass
    except Exception as exc:
        logger.warning("pdfplumber parse failed for %r: %s", pdf_path, exc)

    if not blocks:
        try:
            from pypdf import PdfReader  # type: ignore
            parser_used = "pypdf"
            reader = PdfReader(pdf_path)
            for idx, page in enumerate(reader.pages):
                page_no = idx + 1
                text = page.extract_text() or ""
                if not text.strip():
                    continue
                section = "body"
                for sec_name, pattern in _SECTION_PATTERNS.items():
                    if pattern.search(text[:200]):
                        section = sec_name
                        break
                blocks.append(PageBlock(page_no=page_no, text=text, section_hint=section))
        except ImportError:
            pass
        except Exception as exc:
            logger.warning("pypdf parse failed for %r: %s", pdf_path, exc)

    if not blocks:
        logger.warning(
            "No PDF parser available (install pdfplumber or pypdf), or parsing failed for %r",
            pdf_path,
        )
    elif parser_used:
        logger.debug("Parsed PDF %r with %s (%d pages with text)", pdf_path, parser_used, len(blocks))

    return blocks


def build_page_pool(blocks: list[PageBlock]) -> dict[int, str]:
    """
    Build a mapping {page_no → text} from parsed blocks.

    This pool is used by post_validate_evidence_page() to verify LLM output.
    """
    return {b.page_no: b.text for b in blocks}


def format_with_page_markers(blocks: list[PageBlock]) -> str:
    """
    Produce a single string with explicit [Page N] markers for each block.

    This string is fed to the LLM Prompt.  The LLM must copy the page number
    from the [Page N] marker — never invent it.

    Example output:
        [Page 3] LIMITATIONS:
        The crosstalk between waveguides remains below -20 dB only when ...

        [Page 4] DISCUSSION:
        ...
    """
    parts: list[str] = []
    for b in blocks:
        header = f"[Page {b.page_no}]"
        if b.section_hint != "body":
            header += f" {b.section_hint.upper()}"
        parts.append(f"{header}:\n{b.text.strip()}")
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Post-validation  [AUDIT-015]
# ---------------------------------------------------------------------------

def post_validate_evidence_page(
    page_no: Optional[int],
    page_pool: dict[int, str],
) -> bool:
    """
    Validate that a page_no returned by the LLM actually exists in the
    parsed page pool.

    [AUDIT-015] This is the guard that prevents hallucinated page numbers
    from entering the evidence chain.

    Args:
        page_no:   The page number from the LLM's JSON output.
        page_pool: {page_no → text} built from pdfplumber parse results.

    Returns:
        True  if page_no is in the pool (valid).
        False if page_no is None or not in the pool (reject this evidence).
    """
    if page_no is None:
        logger.warning("post_validate_evidence_page: page_no is None — rejecting")
        return False
    if page_no not in page_pool:
        logger.warning(
            f"post_validate_evidence_page: page_no={page_no} not in parsed pool "
            f"(valid pages: {sorted(page_pool.keys())[:10]}) — rejecting"
        )
        return False
    return True
